### ISSUE TITLE
Landing Page Development

### ISSUE THREAD

**Issue by rskikuli** [uracreative/identihub.org#1]
### Priority
low

### What needs to be done
prepare the environment to install Github pages

### When does it need to be done
1.12.2017

### Other comments
Ideal scenario: @giannisk collaborate with @silvaarapi to show the process as a learning curve

**Comment by AnXh3L0** [comment]
*@anxhelo attached a* [message](https://chat.ura.design/ura-design/pl/5wdt86au97bhmkf696q7hifmgo) *from @anxhelo*
Updates
